FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc g++ && apt-get clean

COPY requirements.txt .
RUN pip install --prefer-binary -r requirements.txt
RUN pip install fastapi uvicorn[standard]

COPY api.py .
COPY monitoring.py .
COPY logging_config.py .

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
